development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: fedena_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: fedena_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: fedena_production
  pool: 5

cucumber:
  <<: *test
