development:
  adapter: mysql
  host: localhost
  database: fedena_development
  pool: 5

test: &test
  adapter: mysql
  host: localhost
  database: fedena_test
  pool: 5

production:
  adapter: mysql
  host: localhost
  database: fedena_production
  pool: 5

cucumber:
  <<: *test
